/** @type {import('tailwindcss').Config} */
// Tokens do design system "Serene Clinical Interface" (ver stitch/.../DESIGN.md)
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        // Tokens "temáveis": apontam para variáveis CSS que o Perfil pode
        // redefinir em tempo real. O valor após a vírgula é o padrão (roxo),
        // usado enquanto o usuário não personaliza nenhuma cor.
        'surface-container-highest': 'var(--c-surface-container-highest, #ecdeee)',
        surface: 'var(--c-surface, #fff7fc)',
        'surface-container-low': 'var(--c-surface-container-low, #fdefff)',
        'secondary-container': 'var(--c-secondary-container, #f5b7fe)',
        'surface-tint': 'var(--c-surface-tint, #942cb0)',
        secondary: 'var(--c-secondary, #7e4a8a)',
        'on-secondary-container': 'var(--c-on-secondary-container, #754281)',
        'inverse-primary': 'var(--c-inverse-primary, #f3aeff)',
        'surface-container': 'var(--c-surface-container, #f8e9fa)',
        'surface-container-high': 'var(--c-surface-container-high, #f2e4f4)',
        'primary-container': 'var(--c-primary-container, #8e24aa)',
        'on-primary-container': 'var(--c-on-primary-container, #f7bcff)',
        primary: 'var(--c-primary, #70008b)',
        'surface-variant': 'var(--c-surface-variant, #ecdeee)',
        'tertiary-container': 'var(--c-tertiary-container, #6b4f72)',
        'on-tertiary-container': 'var(--c-on-tertiary-container, #e8c4ee)',
        background: 'var(--c-background, #fff7fc)',
        'surface-bright': 'var(--c-surface, #fff7fc)',
        // Tokens fixos (contraste/estrutura — não mudam com o tema).
        'on-surface-variant': '#504251',
        'primary-fixed-dim': '#f3aeff',
        'on-error': '#ffffff',
        'surface-dim': '#e3d6e5',
        'surface-container-lowest': '#ffffff',
        'on-surface': '#201924',
        'secondary-fixed': '#fdd6ff',
        'on-primary': '#ffffff',
        'primary-fixed': '#fdd6ff',
        'secondary-fixed-dim': '#efb1f9',
        'on-tertiary-fixed-variant': '#583d5f',
        'inverse-on-surface': '#faecfc',
        'on-primary-fixed': '#340042',
        'on-secondary': '#ffffff',
        'tertiary-fixed-dim': '#debbe4',
        'on-error-container': '#93000a',
        'tertiary-fixed': '#fad7ff',
        'outline-variant': '#d3c1d2',
        'on-secondary-fixed-variant': '#643370',
        'on-tertiary-fixed': '#291231',
        'on-background': '#201924',
        error: '#ba1a1a',
        tertiary: '#523859',
        'error-container': '#ffdad6',
        'on-tertiary': '#ffffff',
        'on-primary-fixed-variant': '#790096',
        outline: '#827282',
        'inverse-surface': '#362e39',
        'on-secondary-fixed': '#340141',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        '2xl': '1rem',
        full: '9999px',
      },
      spacing: {
        'margin-safe': '32px',
        'max-width': '1280px',
        'stack-md': '2rem',
        'stack-xs': '0.5rem',
        'stack-sm': '1rem',
        'stack-lg': '4rem',
        gutter: '24px',
      },
      maxWidth: {
        'max-width': '1280px',
      },
      fontFamily: {
        sans: ['Inter', 'system-ui', 'sans-serif'],
        'button-text': ['Inter'],
        'headline-lg': ['Inter'],
        'headline-md': ['Inter'],
        'label-lg': ['Inter'],
        'body-lg': ['Inter'],
        'body-md': ['Inter'],
      },
      fontSize: {
        'button-text': ['20px', { lineHeight: '1.2', fontWeight: '600' }],
        'headline-lg': ['32px', { lineHeight: '1.2', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-md': ['24px', { lineHeight: '1.3', fontWeight: '600' }],
        'label-lg': ['18px', { lineHeight: '1.2', fontWeight: '600' }],
        'body-lg': ['20px', { lineHeight: '1.6', fontWeight: '400' }],
        'body-md': ['18px', { lineHeight: '1.6', fontWeight: '400' }],
      },
      keyframes: {
        fadeIn: {
          from: { opacity: '0', transform: 'translateY(20px)' },
          to: { opacity: '1', transform: 'translateY(0)' },
        },
        zoomIn: {
          from: { opacity: '0', transform: 'scale(0.95)' },
          to: { opacity: '1', transform: 'scale(1)' },
        },
      },
      animation: {
        'fade-in': 'fadeIn 0.5s cubic-bezier(0.16, 1, 0.3, 1) forwards',
        'zoom-in': 'zoomIn 0.25s ease-out forwards',
      },
    },
  },
  plugins: [require('@tailwindcss/forms')],
};
